///////////////////////////////////////////////////////////////////////////////
// CPPVP1Services.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_CPPVP1 = 0x3F000000;
#define SRVNAME_CPPVP1 "CPPVP1"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_CPPVP1CSignalsDemo = {0x1cff1d80,0x18db,0x2a28,{0x93,0x29,0x4a,0x07,0xaa,0xfd,0x61,0x1d}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_SignalsDemoParameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_E760036D_C10D_43F8_BEC9_170FBF97FE62_INCLUDED_)
#define _TC_TYPE_E760036D_C10D_43F8_BEC9_170FBF97FE62_INCLUDED_
enum E_FourierType : SHORT {
	Square = 0,
	Sawtooth = 1,
	Triangle = 2,
	Fibonacci = 3,
	Pulse = 4
};
#endif // !defined(_TC_TYPE_E760036D_C10D_43F8_BEC9_170FBF97FE62_INCLUDED_)

typedef struct _SignalsDemoParameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} SignalsDemoParameter, *PSignalsDemoParameter;

#pragma pack(push,1)
typedef struct _SignalsDemoOutputs
{
	double Value;
	ULONG TaskCycleTime;
} SignalsDemoOutputs, *PSignalsDemoOutputs;
#pragma pack(pop)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_SignalsDemoOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
