///////////////////////////////////////////////////////////////////////////////
// CPPVP1ClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "CPPVP1ClassFactory.h"
#include "CPPVP1Services.h"
#include "CPPVP1Version.h"
#include "SignalsDemo.h"

BEGIN_CLASS_MAP(CCPPVP1ClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_CPPVP1, CID_CPPVP1CSignalsDemo, SRVNAME_CPPVP1 "!CSignalsDemo", CSignalsDemo)
///</AutoGeneratedContent>
END_CLASS_MAP()

CCPPVP1ClassFactory::CCPPVP1ClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_CPPVP1));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(CPPVP1));
#endif //defined(TCDBG_UNIT_VERSION)
}

