///////////////////////////////////////////////////////////////////////////////
// SignalsDemo.h
#pragma once

#include "CPPVP1Interfaces.h"

class CSignalsDemo 
	: public ITComObject
///<AutoGeneratedContent id="InheritanceList">
	, public ITComOnlineChange
	, public ITcCyclic
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST_LIB()
	DECLARE_ITCOMOBJECT_LOCKOP()

	CSignalsDemo();
	virtual	~CSignalsDemo();

///<AutoGeneratedContent id="InterfaceMembers">
	// ITComOnlineChange
	virtual HRESULT TCOMAPI PrepareOnlineChange(ITComObject* ipOldObj, TmcInstData* pOldInfo);
	virtual HRESULT TCOMAPI PerformOnlineChange(ITComObject* ipOldObj, TmcInstData* pOldInfo);

	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

///</AutoGeneratedContent>

	double CSignalsDemo::CalcTheta(double frequency);
	double CSignalsDemo::CalcCoefficient(int N);
	double CSignalsDemo::GenerateSignal(int harmonic, double amplitude, double frequency);

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	// Tracing
	CTcTrace m_Trace;

///<AutoGeneratedContent id="Members">
	TcTraceLevel m_TraceLevelMax;
	SignalsDemoParameter m_Parameter;
	SignalsDemoOutputs* m_pOutputs;
///</AutoGeneratedContent>

	ITcADIPtr m_spADI;

	// Used for signal generation
	E_FourierType SignalType;
	double _Theta;
	double _TaskTime;
	int harmonics = 12;
	double amplitude = 1.0;
	double frequency = 1.00; // Frequency in Hz

};
